# Generated by Django 4.1.3 on 2022-11-26 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SchoolInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "management_name",
                    models.CharField(default="Management Name", max_length=200),
                ),
                (
                    "school_name",
                    models.CharField(default="Your School Name", max_length=200),
                ),
                (
                    "school_short_name",
                    models.CharField(default="R.G.S", max_length=200),
                ),
                (
                    "school_code",
                    models.CharField(default="Your School Code", max_length=200),
                ),
                (
                    "address",
                    models.CharField(default="Your School Address", max_length=200),
                ),
                (
                    "phone",
                    models.CharField(default="Your School Phone", max_length=200),
                ),
                (
                    "email",
                    models.EmailField(
                        default="yourschoolemail@domain.com", max_length=200
                    ),
                ),
                (
                    "session",
                    models.CharField(
                        choices=[
                            ("2010-11", "2010-11"),
                            ("2011-12", "2011-12"),
                            ("2012-13", "2012-13"),
                            ("2013-14", "2013-14"),
                            ("2014-15", "2014-15"),
                            ("2015-16", "2015-16"),
                            ("2016-17", "2016-17"),
                            ("2017-18", "2017-18"),
                            ("2018-19", "2018-19"),
                            ("2019-20", "2019-20"),
                            ("2020-21", "2020-21"),
                            ("2021-22", "2021-22"),
                            ("2022-23", "2022-23"),
                            ("2023-24", "2023-24"),
                            ("2024-25", "2024-25"),
                            ("2025-26", "2025-26"),
                            ("2026-27", "2026-27"),
                            ("2027-28", "2027-28"),
                            ("2028-29", "2028-29"),
                            ("2029-30", "2029-30"),
                            ("2030-31", "2030-31"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="Session ",
                    ),
                ),
            ],
            options={
                "verbose_name": "school info",
                "verbose_name_plural": "school info",
            },
        ),
        migrations.CreateModel(
            name="SelectedSchool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "school",
                    models.OneToOneField(
                        help_text="<p class='ml-2'><small>Select Your Current School That You Want To Work On.</small></p>",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configurations.schoolinfo",
                        verbose_name="Selected School",
                    ),
                ),
            ],
        ),
    ]
