# Generated by Django 4.1.3 on 2022-11-26 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("configurations", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="selectedschool",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.superadmin",
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="schoolinfo",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.superadmin",
                verbose_name="User",
            ),
        ),
    ]
