# Generated by Django 4.1.3 on 2022-11-15 12:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Selected_School',
            new_name='SelectedSchool',
        ),
    ]
