# Generated by Django 4.1.3 on 2022-11-16 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0002_rename_selected_school_selectedschool'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolinfo',
            options={'verbose_name': 'school info', 'verbose_name_plural': 'school info'},
        ),
        migrations.AlterField(
            model_name='selectedschool',
            name='school',
            field=models.OneToOneField(help_text="<p class='ml-2'><small>Select Your Current School That You Want To Work On.</small></p>", on_delete=django.db.models.deletion.CASCADE, to='configurations.schoolinfo', verbose_name='Selected School'),
        ),
    ]
