# Generated by Django 4.1.3 on 2022-11-26 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("configurations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subjectgroup",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="configurations.schoolinfo",
                verbose_name="school name",
            ),
        ),
        migrations.AddField(
            model_name="subjectgroup",
            name="section",
            field=models.ManyToManyField(to="academics.section"),
        ),
        migrations.AddField(
            model_name="subjectgroup",
            name="subject",
            field=models.ManyToManyField(
                to="academics.subject", verbose_name="subject"
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="configurations.schoolinfo",
                verbose_name="school name",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="configurations.schoolinfo",
                verbose_name="school name",
            ),
        ),
        migrations.AddField(
            model_name="designation",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="configurations.schoolinfo",
                verbose_name="school name",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="configurations.schoolinfo",
                verbose_name="school name",
            ),
        ),
        migrations.AddField(
            model_name="classes",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="configurations.schoolinfo",
                verbose_name="school name",
            ),
        ),
        migrations.AddField(
            model_name="classes",
            name="section",
            field=models.ManyToManyField(
                to="academics.section", verbose_name="Section"
            ),
        ),
        migrations.AddField(
            model_name="assignclassteacher",
            name="class_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="academics.classes",
                verbose_name="class",
            ),
        ),
        migrations.AddField(
            model_name="assignclassteacher",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="configurations.schoolinfo",
                verbose_name="school name",
            ),
        ),
        migrations.AddField(
            model_name="assignclassteacher",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="academics.section",
                verbose_name="section",
            ),
        ),
    ]
