# Generated by Django 4.1.3 on 2022-11-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0002_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignclassteacher",
            name="teacher",
            field=models.ManyToManyField(to="users.teacher", verbose_name="teachers"),
        ),
        migrations.AlterUniqueTogether(
            name="subject",
            unique_together={("subject_name", "school")},
        ),
        migrations.AlterUniqueTogether(
            name="assignclassteacher",
            unique_together={("class_name", "section", "school")},
        ),
    ]
